#Q1

In [ ]:
Ordinal assigns integer values basis the natural order, tall medium short 
Label assigns integer without any ranking.

In [1]:
#Q2

In [ ]:
Taking help of target variable to encode data. 

Ranking kids basis their marks. 

In [2]:
#Q3

In [ ]:
Covariance and correlation are both statistical concepts that help us understand the relationship between two variables.

Covariance measures the direction of the relationship vs correaltion measure it's strength. 

In [ ]:
Covariance shows how two variables fluctuate with each other, same direction movement positive covariance and oppostite direction 
movement Negative Covariance. 

CoRelation shows how strongly two variables are associated with each other, It describes how a change in one variable leads to change in the
% change in second variable. 
Co relation values are standardized and range from +1 to -1, with extreme values indicating a strong relationship. A corelation value of 0 indicates 
no linear relationship within variables. 

In [ ]:
numpy.cov()

In [3]:
#Q4

In [62]:
import pandas as pd
df = pd.DataFrame({'Name' : ('A','B','C'), 'Color' : ('red','green','blue'), 'size' : ('small','medium','large'), 'material' : ('wood','metal','plastic')})

In [47]:
new_row = {'Name':'D','Color':'blue','size':'small','material':'metal'}

In [63]:
new_row2 = {'E','red','medium','plastic'}

In [65]:
df = df._append(new_row,ignore_index=True)

In [66]:
df

Name  Color    size material
0    A    red   small     wood
1    B  green  medium    metal
2    C   blue   large  plastic
3    D   blue   small    metal

In [12]:
from sklearn.preprocessing import LabelEncoder

In [67]:
le = LabelEncoder()

In [71]:
le1 = le.fit_transform(df[['Color','size','material']]).toarray()

ValueError: y should be a 1d array, got an array of shape (4, 3) instead.

In [19]:
A1 = le.transform(df['Color'])

In [25]:
A1

array([2, 1, 0])

In [72]:
#Q5

In [73]:
df = pd.DataFrame({'Name':("Nitesh","Ramesh","Suresh"), 'Age' :(30,35,40),'income' : (100,200,400), 'Education' : ('Graduate','post-Graduate','Graduate')})

In [74]:
df

Name  Age  income      Education
0  Nitesh   30     100       Graduate
1  Ramesh   35     200  post-Graduate
2  Suresh   40     400       Graduate

In [75]:
import numpy as np

In [76]:
np.cov(df['Age'],df['income'])

array([[   25.        ,   750.        ],
       [  750.        , 23333.33333333]])

In [80]:
# Python code to demonstrate the 
# use of numpy.cov
import numpy as np

x = [1.23, 2.12, 3.34, 4.5]

y = [2.56, 2.89, 3.76, 3.95]

# find out covariance with respect  columns
cov_mat = np.stack((x, y), axis = 1) 

print(np.cov(cov_mat))

[[ 0.88445  0.51205  0.2793  -0.36575]
 [ 0.51205  0.29645  0.1617  -0.21175]
 [ 0.2793   0.1617   0.0882  -0.1155 ]
 [-0.36575 -0.21175 -0.1155   0.15125]]
